# Generated by Django 6.1 on 2026-10-05 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=10, verbose_name='teléfono')),
                ('cargo', models.CharField(blank=True, help_text='Puesto o función en el colegio.', max_length=80)),
                ('debe_cambiar_contrasena', models.BooleanField(default=False, help_text='Se activa al crear la cuenta o restablecer la contraseña: en su siguiente acceso deberá elegir una propia.', verbose_name='debe cambiar su contraseña')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de usuario',
                'verbose_name_plural': 'perfiles de usuario',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('tono', models.PositiveSmallIntegerField(choices=[(1, 'Turquesa'), (2, 'Amarillo'), (3, 'Guinda'), (4, 'Azul'), (5, 'Verde'), (6, 'Gris')], default=1, verbose_name='color')),
                ('activo', models.BooleanField(default=True, help_text='Un rol desactivado no se puede asignar a usuarios nuevos. No se borra: conserva su historial.')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los roles del sistema no se pueden editar ni desactivar.', verbose_name='rol del sistema')),
                ('acceso_total', models.BooleanField(default=False, help_text='Quien tiene este rol puede hacer todo en el sistema (y entrar a la administración de Django).')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='auth.group', verbose_name='grupo de permisos')),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'ordering': ['-acceso_total', 'grupo__name'],
            },
        ),
    ]
