# Generated by Django 6.1 on 2026-10-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_rol_es_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=False, help_text='Si está activo, en su siguiente acceso deberá elegir una contraseña propia. Es opcional: se pide al crear la cuenta o al restablecer su contraseña.', verbose_name='debe cambiar su contraseña'),
        ),
    ]
