# Generated by Django 6.1 on 2026-09-02 18:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=20, unique=True, verbose_name='Referencia')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=60, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=60, verbose_name='Apellido materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nacionalidad', models.CharField(default='Mexicana', max_length=50, verbose_name='Nacionalidad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguíneo')),
                ('religion', models.CharField(blank=True, max_length=80, verbose_name='Religión')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')], verbose_name='Código postal')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso')),
                ('escuela_procedencia', models.CharField(blank=True, max_length=200, verbose_name='Escuela de procedencia')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('foto_url', models.URLField(blank=True, max_length=500, verbose_name='URL de la foto')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('EGRESADO', 'Egresado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
    ]
