# Generated by Django 6.1 on 2026-09-14 02:24

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='UID de tarjeta')),
                ('referencia', models.CharField(max_length=20, unique=True, verbose_name='Referencia')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=60, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=60, verbose_name='Apellido materno')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nacionalidad', models.CharField(default='Mexicana', max_length=50, verbose_name='Nacionalidad')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('grupo_sanguineo', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, verbose_name='Grupo sanguíneo')),
                ('religion', models.CharField(blank=True, max_length=80, verbose_name='Religión')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('cp', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')], verbose_name='Código postal')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha de ingreso')),
                ('escuela_procedencia', models.CharField(blank=True, max_length=200, verbose_name='Escuela de procedencia')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='alumnos/', verbose_name='Fotografía')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('contrasena', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('BAJA', 'Baja'), ('EGRESADO', 'Egresado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'alumnos',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Ciclo escolar')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo escolar',
                'verbose_name_plural': 'Ciclos escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria')], max_length=20)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'constraints': [models.UniqueConstraint(fields=('nivel', 'numero'), name='grado_nivel_numero_unico')],
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.localdate)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.alumno')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.grado')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_generales', to='Alumnos.inscripcion')),
            ],
            options={
                'verbose_name': 'Asistencia general',
                'verbose_name_plural': 'Asistencias generales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MateriaGrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_grado', to='Alumnos.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materias_grado', to='Alumnos.grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grados_materia', to='Alumnos.materia')),
            ],
            options={
                'verbose_name': 'Materia del grado',
                'verbose_name_plural': 'Materias del grado',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('justifica_general', models.BooleanField(default=False, verbose_name='Justificar asistencia general')),
                ('todas_materias', models.BooleanField(default=False, verbose_name='Justificar todas las materias')),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/', verbose_name='Comprobante')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='Alumnos.inscripcion')),
                ('materias', models.ManyToManyField(blank=True, related_name='justificaciones', to='Alumnos.materiagrado')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='HorarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('materia_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Alumnos.materiagrado')),
            ],
            options={
                'verbose_name': 'Horario de materia',
                'verbose_name_plural': 'Horarios de materias',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_materias', to='Alumnos.inscripcion')),
                ('materia_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='Alumnos.materiagrado')),
            ],
            options={
                'verbose_name': 'Asistencia por materia',
                'verbose_name_plural': 'Asistencias por materia',
            },
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'ciclo'), name='alumno_ciclo_unico'),
        ),
        migrations.AddIndex(
            model_name='asistenciageneral',
            index=models.Index(fields=['fecha'], name='Alumnos_asi_fecha_370ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciageneral',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='asistencia_general_unica'),
        ),
        migrations.AddConstraint(
            model_name='materiagrado',
            constraint=models.UniqueConstraint(fields=('ciclo', 'grado', 'materia'), name='materia_grado_ciclo_unica'),
        ),
        migrations.AddConstraint(
            model_name='justificacion',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='justificacion_alumno_fecha_unica'),
        ),
        migrations.AddIndex(
            model_name='asistenciamateria',
            index=models.Index(fields=['fecha'], name='Alumnos_asi_fecha_107e6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciamateria',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'materia_grupo', 'fecha'), name='asistencia_materia_unica'),
        ),
    ]
