# Generated by Django 6.1 on 2026-09-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='alumno',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
    ]
