# Generated by Django 6.1 on 2026-09-14 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asistenciageneral',
            options={'ordering': ['-fecha', '-creado'], 'verbose_name': 'Asistencia general', 'verbose_name_plural': 'Asistencias generales'},
        ),
        migrations.AlterModelOptions(
            name='asistenciamateria',
            options={'ordering': ['-fecha', '-creado'], 'verbose_name': 'Asistencia por materia', 'verbose_name_plural': 'Asistencias por materia'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['nivel', 'numero'], 'verbose_name': 'Grado', 'verbose_name_plural': 'Grados'},
        ),
        migrations.AlterModelOptions(
            name='justificacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Justificación', 'verbose_name_plural': 'Justificaciones'},
        ),
        migrations.AlterModelOptions(
            name='materiagrado',
            options={'ordering': ['grado', 'materia__nombre'], 'verbose_name': 'Materia del grado', 'verbose_name_plural': 'Materias del grado'},
        ),
        migrations.RemoveConstraint(
            model_name='asistenciamateria',
            name='asistencia_materia_unica',
        ),
        migrations.RenameField(
            model_name='asistenciamateria',
            old_name='materia_grupo',
            new_name='materia_grado',
        ),
        migrations.RenameField(
            model_name='horariomateria',
            old_name='materia_grupo',
            new_name='materia_grado',
        ),
        migrations.AlterField(
            model_name='asistenciageneral',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asistenciageneral',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistenciageneral',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='asistenciamateria',
            name='estado',
            field=models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='asistenciamateria',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='asistenciamateria',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='cicloescolar',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel',
            field=models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria')], max_length=20, verbose_name='Nivel'),
        ),
        migrations.AlterField(
            model_name='horariomateria',
            name='dia_semana',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día'),
        ),
        migrations.AlterField(
            model_name='horariomateria',
            name='hora_fin',
            field=models.TimeField(verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='horariomateria',
            name='hora_inicio',
            field=models.TimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de inscripción'),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='materias',
            field=models.ManyToManyField(blank=True, related_name='justificaciones', to='Alumnos.materiagrado', verbose_name='Materias'),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='motivo',
            field=models.TextField(verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='clave',
            field=models.CharField(max_length=20, unique=True, verbose_name='Clave'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materiagrado',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AddConstraint(
            model_name='asistenciamateria',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'materia_grado', 'fecha'), name='asistencia_materia_unica'),
        ),
        migrations.AddConstraint(
            model_name='horariomateria',
            constraint=models.UniqueConstraint(fields=('materia_grado', 'dia_semana', 'hora_inicio', 'hora_fin'), name='horario_materia_unico'),
        ),
    ]
