# Generated by Django 6.1 on 2026-09-14 04:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_alter_asistenciageneral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=60, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=60, verbose_name='Apellido materno')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión libre'), ('OTRO', 'Otro')], max_length=20, verbose_name='Estado civil')),
                ('religion', models.CharField(blank=True, max_length=80, verbose_name='Religión')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono alternativo')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('domicilio', models.CharField(blank=True, max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('cp', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')], verbose_name='Código postal')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('lugar_trabajo', models.CharField(blank=True, max_length=150, verbose_name='Lugar de trabajo')),
                ('telefono_trabajo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del trabajo')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TutorAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('ABUELA', 'Abuela'), ('ABUELO', 'Abuelo'), ('HERMANA', 'Hermana'), ('HERMANO', 'Hermano'), ('TIA', 'Tía'), ('TIO', 'Tío'), ('TUTOR_LEGAL', 'Tutor legal'), ('OTRO', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('tutor_principal', models.BooleanField(default=False, verbose_name='Tutor principal')),
                ('contacto_emergencia', models.BooleanField(default=False, verbose_name='Contacto de emergencia')),
                ('autorizado_recoger', models.BooleanField(default=False, verbose_name='Autorizado para recoger al alumno')),
                ('recibe_notificaciones', models.BooleanField(default=True, verbose_name='Recibe notificaciones')),
                ('responsable_pagos', models.BooleanField(default=False, verbose_name='Responsable de pagos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores_relacionados', to='Alumnos.alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_relacionados', to='Alumnos.tutor')),
            ],
            options={
                'verbose_name': 'Tutor del alumno',
                'verbose_name_plural': 'Tutores de alumnos',
                'constraints': [models.UniqueConstraint(fields=('tutor', 'alumno'), name='tutor_alumno_unico')],
            },
        ),
    ]
