# Generated by Django 6.1 on 2026-09-06 22:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0002_remove_alumno_foto_url_alumno_fotografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('nacionalidad', models.CharField(default='Mexicana', max_length=50, verbose_name='Nacionalidad')),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a'), ('UNION_LIBRE', 'Unión libre'), ('SEPARADO', 'Separado/a'), ('OTRO', 'Otro')], max_length=20, verbose_name='Estado civil')),
                ('religion', models.CharField(blank=True, max_length=80, verbose_name='Religión')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('telefono_oficina', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de oficina')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('domicilio', models.CharField(blank=True, max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('cp', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')], verbose_name='Código postal')),
            ],
            options={
                'verbose_name': 'Tutor',
                'verbose_name_plural': 'Tutores',
                'db_table': 'tutores',
                'ordering': ['apellidos', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AlumnoTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=20, verbose_name='Parentesco')),
                ('contacto_principal', models.BooleanField(default=False, verbose_name='Contacto principal')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores', to='Alumnos.alumno', verbose_name='Alumno')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='Alumnos.tutor', verbose_name='Tutor')),
            ],
            options={
                'verbose_name': 'Relación alumno-tutor',
                'verbose_name_plural': 'Relaciones alumno-tutor',
                'db_table': 'alumno_tutor',
                'constraints': [models.UniqueConstraint(fields=('alumno', 'tutor'), name='unique_alumno_tutor')],
            },
        ),
    ]
