# Generated by Django 6.1 on 2026-09-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_tutor_alumnotutor'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alumnotutor',
            name='unique_alumno_tutor',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/', verbose_name='Fotografía'),
        ),
        migrations.DeleteModel(
            name='AlumnoTutor',
        ),
        migrations.DeleteModel(
            name='Tutor',
        ),
    ]
