# Generated by Django 6.1 on 2026-10-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_tutor_tutoralumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
