# Generated by Django 6.1 on 2026-09-09 01:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_remove_alumnotutor_unique_alumno_tutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CicloEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='Ciclo escolar')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciclo escolar',
                'verbose_name_plural': 'Ciclos escolares',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria')], max_length=20)),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Grado')),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'constraints': [models.UniqueConstraint(fields=('nivel', 'numero'), name='grado_nivel_numero_unico')],
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Grupo')),
                ('activo', models.BooleanField(default=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='Alumnos.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='Alumnos.grado')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateField(default=django.utils.timezone.localdate)),
                ('activa', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.grupo')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_generales', to='Alumnos.inscripcion')),
            ],
            options={
                'verbose_name': 'Asistencia general',
                'verbose_name_plural': 'Asistencias generales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MateriaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activa', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_grupo', to='Alumnos.grupo')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_materia', to='Alumnos.materia')),
            ],
            options={
                'verbose_name': 'Materia del grupo',
                'verbose_name_plural': 'Materias del grupo',
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.TextField()),
                ('justifica_general', models.BooleanField(default=False, verbose_name='Justificar asistencia general')),
                ('todas_materias', models.BooleanField(default=False, verbose_name='Justificar todas las materias')),
                ('documento', models.FileField(blank=True, null=True, upload_to='justificaciones/%Y/%m/', verbose_name='Comprobante')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='Alumnos.inscripcion')),
                ('materias', models.ManyToManyField(blank=True, related_name='justificaciones', to='Alumnos.materiagrupo')),
            ],
            options={
                'verbose_name': 'Justificación',
                'verbose_name_plural': 'Justificaciones',
            },
        ),
        migrations.CreateModel(
            name='HorarioMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('materia_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='Alumnos.materiagrupo')),
            ],
            options={
                'verbose_name': 'Horario de materia',
                'verbose_name_plural': 'Horarios de materias',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('FALTA', 'Falta'), ('RETARDO', 'Retardo')], default='PRESENTE', max_length=15)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias_materias', to='Alumnos.inscripcion')),
                ('materia_grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='Alumnos.materiagrupo')),
            ],
            options={
                'verbose_name': 'Asistencia por materia',
                'verbose_name_plural': 'Asistencias por materia',
            },
        ),
        migrations.AddConstraint(
            model_name='grupo',
            constraint=models.UniqueConstraint(fields=('ciclo', 'grado', 'nombre'), name='grupo_unico_por_ciclo'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'grupo'), name='alumno_grupo_unico'),
        ),
        migrations.AddIndex(
            model_name='asistenciageneral',
            index=models.Index(fields=['fecha'], name='Alumnos_asi_fecha_370ed2_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciageneral',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='asistencia_general_unica'),
        ),
        migrations.AddConstraint(
            model_name='materiagrupo',
            constraint=models.UniqueConstraint(fields=('grupo', 'materia'), name='materia_grupo_unica'),
        ),
        migrations.AddConstraint(
            model_name='justificacion',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='justificacion_alumno_fecha_unica'),
        ),
        migrations.AddIndex(
            model_name='asistenciamateria',
            index=models.Index(fields=['fecha'], name='Alumnos_asi_fecha_107e6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='asistenciamateria',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'materia_grupo', 'fecha'), name='asistencia_materia_unica'),
        ),
    ]
