# Generated by Django 6.1 on 2026-10-04 18:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_grado_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=60, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=60, verbose_name='Apellido materno')),
                ('curp', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CURP')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono alternativo')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo electrónico')),
                ('domicilio', models.CharField(blank=True, max_length=200, verbose_name='Domicilio')),
                ('colonia', models.CharField(blank=True, max_length=100, verbose_name='Colonia')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(blank=True, max_length=100, verbose_name='Estado')),
                ('cp', models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(message='El código postal debe contener exactamente 5 dígitos.', regex='^\\d{5}$')], verbose_name='Código postal')),
                ('profesion', models.CharField(blank=True, max_length=150, verbose_name='Profesión o título')),
                ('cedula_profesional', models.CharField(blank=True, max_length=20, verbose_name='Cédula profesional')),
                ('especialidad', models.CharField(blank=True, max_length=150, verbose_name='Especialidad o áreas que imparte')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso al colegio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estatus', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20, verbose_name='Estatus')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='materiagrado',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='Alumnos.profesor', verbose_name='Profesor'),
        ),
    ]
