# Generated by Django 6.1 on 2026-10-04 19:45

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_profesor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('cerrado_en', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Cerrado el')),
                ('automatico', models.BooleanField(default=False, verbose_name='Cierre automático')),
                ('faltas', models.PositiveIntegerField(default=0, verbose_name='Faltas generadas')),
            ],
            options={
                'verbose_name': 'Cierre de día',
                'verbose_name_plural': 'Cierres de día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_entrada', models.TimeField(default=datetime.time(8, 0), verbose_name='Hora de entrada')),
                ('tolerancia_minutos', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(120)], verbose_name='Tolerancia (minutos)')),
                ('cierre_automatico', models.BooleanField(default=True, verbose_name='Cerrar automáticamente los días anteriores')),
            ],
            options={
                'verbose_name': 'Configuración de asistencia',
                'verbose_name_plural': 'Configuración de asistencia',
            },
        ),
        migrations.CreateModel(
            name='DiaNoLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('motivo', models.CharField(max_length=120, verbose_name='Motivo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Día sin clases',
                'verbose_name_plural': 'Días sin clases',
                'ordering': ['fecha'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='justificacion',
            name='justificacion_alumno_fecha_unica',
        ),
        migrations.AddField(
            model_name='asistenciageneral',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de entrada'),
        ),
        migrations.AddField(
            model_name='asistenciageneral',
            name='origen',
            field=models.CharField(choices=[('UID', 'Credencial (UID)'), ('REFERENCIA', 'Número de referencia'), ('MANUAL', 'Captura manual'), ('CIERRE', 'Cierre del día')], default='MANUAL', max_length=12, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='asistenciageneral',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='asistenciamateria',
            name='origen',
            field=models.CharField(choices=[('ENTRADA', 'Entrada del alumno'), ('PASE', 'Pase de lista'), ('MANUAL', 'Captura manual'), ('CIERRE', 'Cierre del día')], default='PASE', max_length=10, verbose_name='Origen'),
        ),
        migrations.AddField(
            model_name='asistenciamateria',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='registrada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por'),
        ),
        migrations.AddConstraint(
            model_name='justificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('activa', True)), fields=('inscripcion', 'fecha'), name='justificacion_alumno_fecha_unica'),
        ),
        migrations.AddField(
            model_name='cierredia',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
    ]
