# Generated by Django 6.1 on 2026-10-06 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0006_asistencias_kiosco'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombre'], 'verbose_name': 'Estudiante', 'verbose_name_plural': 'Estudiantes'},
        ),
        migrations.AlterModelOptions(
            name='tutoralumno',
            options={'verbose_name': 'Tutor del estudiante', 'verbose_name_plural': 'Tutores de estudiantes'},
        ),
        migrations.AlterField(
            model_name='asistenciamateria',
            name='origen',
            field=models.CharField(choices=[('ENTRADA', 'Entrada del estudiante'), ('PASE', 'Pase de lista'), ('MANUAL', 'Captura manual'), ('CIERRE', 'Cierre del día')], default='PASE', max_length=10, verbose_name='Origen'),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='Alumnos.alumno', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='tutoralumno',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutores_relacionados', to='Alumnos.alumno', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='tutoralumno',
            name='autorizado_recoger',
            field=models.BooleanField(default=False, verbose_name='Autorizado para recoger al estudiante'),
        ),
    ]
