# Generated by Django 6.1 on 2026-10-06 00:49

import django.db.models.deletion
from django.db import migrations, models


def habilitar_a_quienes_ya_imparten(apps, schema_editor):
    """Quien ya da una materia en algún grado y ciclo puede darla: se le habilita para ella (punto de partida)."""
    MateriaGrado = apps.get_model('Alumnos', 'MateriaGrado')
    ProfesorMateria = apps.get_model('Alumnos', 'ProfesorMateria')
    pares = MateriaGrado.objects.filter(profesor__isnull=False).values_list('profesor_id', 'materia_id').distinct()
    ProfesorMateria.objects.bulk_create(
        [ProfesorMateria(profesor_id=profesor, materia_id=materia) for profesor, materia in pares], ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0009_equivalencia_con_letras'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='horas_maximas',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Opcional. Sirve para avisar cuando su carga de clases la rebasa.', null=True, verbose_name='Horas máximas por semana'),
        ),
        migrations.CreateModel(
            name='ProfesorMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones', to='Alumnos.materia')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilitaciones', to='Alumnos.profesor')),
            ],
            options={
                'verbose_name': 'Materia que puede impartir',
                'verbose_name_plural': 'Materias que puede impartir',
                'ordering': ['materia__nombre'],
                'constraints': [models.UniqueConstraint(fields=('profesor', 'materia'), name='profesor_materia_unica')],
            },
        ),
        migrations.RunPython(habilitar_a_quienes_ya_imparten, migrations.RunPython.noop),
    ]
