# Generated by Django 6.1 on 2026-10-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0010_profesores_y_materias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='usuario',
            field=models.OneToOneField(blank=True, help_text='La cuenta con la que entra al sistema. Lo que puede hacer lo define el rol de esa cuenta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesor', to=settings.AUTH_USER_MODEL, verbose_name='Cuenta de acceso'),
        ),
    ]
