# Generated by Django 6.1 on 2026-10-08 03:33

import django.db.models.deletion
from django.db import migrations, models


def niveles_de_lo_que_imparten(apps, schema_editor):
    """Cada profesor queda en los niveles de los grados donde ya imparte (o impartió) alguna materia.

    Quien no tiene ninguna asignación queda sin nivel: se le elige al editarlo. Repetible sin duplicar.
    """
    MateriaGrado = apps.get_model('Alumnos', 'MateriaGrado')
    ProfesorNivel = apps.get_model('Alumnos', 'ProfesorNivel')
    pares = set(
        MateriaGrado.objects.exclude(profesor=None).order_by()
        .values_list('profesor_id', 'grado__nivel').distinct()
    )
    existentes = set(ProfesorNivel.objects.values_list('profesor_id', 'nivel'))
    ProfesorNivel.objects.bulk_create([
        ProfesorNivel(profesor_id=profesor_id, nivel=nivel) for profesor_id, nivel in sorted(pares - existentes)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0013_union_profesor_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorNivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria')], max_length=20, verbose_name='Nivel')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='Alumnos.profesor')),
            ],
            options={
                'verbose_name': 'Nivel en el que da clases',
                'verbose_name_plural': 'Niveles en los que da clases',
                'constraints': [models.UniqueConstraint(fields=('profesor', 'nivel'), name='profesor_nivel_unico')],
            },
        ),
        migrations.RunPython(niveles_de_lo_que_imparten, migrations.RunPython.noop),
    ]
