# Generated by Django 6.1 on 2026-10-09 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0017_materias_en_el_plan_de_su_grado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Recreo', max_length=40, verbose_name='Nombre')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de fin')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recreos', to='Alumnos.cicloescolar')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recreos', to='Alumnos.grado')),
            ],
            options={
                'verbose_name': 'Recreo',
                'verbose_name_plural': 'Recreos',
                'ordering': ['dia_semana', 'hora_inicio'],
            },
        ),
    ]
