# Generated by Django 6.1 on 2026-10-09 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0018_recreo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('PREPARATORIA', 'Preparatoria')], max_length=20, verbose_name='Nivel')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Se abre el')),
                ('fecha_fin', models.DateField(verbose_name='Se cierra el')),
                ('apertura', models.CharField(choices=[('FECHAS', 'Según sus fechas'), ('ABIERTO', 'Abierto a mano'), ('CERRADO', 'Cerrado a mano')], default='FECHAS', max_length=10, verbose_name='Apertura')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='Alumnos.cicloescolar', verbose_name='Ciclo escolar')),
            ],
            options={
                'verbose_name': 'Periodo de evaluación',
                'verbose_name_plural': 'Periodos de evaluación',
                'ordering': ['fecha_inicio', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('ciclo', 'nivel', 'nombre'), name='periodo_nombre_unico_por_nivel')],
            },
        ),
    ]
